blue_media_task_item:
    resource: "@BlueMediaTaskBundle/Resources/config/routing/item.yml"
    prefix:   /

blue_media_task_homepage:
    path:     /
    defaults: { _controller: BlueMediaTaskBundle:Default:index }

blue_media_items:
    type: rest
    pattern:  /items
    resource: "BlueMedia\TaskBundle\Controller\ItemController"

